// THIS FILE IS AUTOMATICALLY GENERATED
loadSprite("test", "development/assets/forest/1.png", {
    sliceX: 1,
    sliceY: 1,
    anims: {
        idle: {
            from: 0,
            to: 0,
            loop: true
        }
    }
});