// THIS FILE IS GENERATED AUTOMATICALLY
loadSprite("10_forestbednight", "/assets/sprites/10_forestbednight.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("11_lookinguptrees", "/assets/sprites/11_lookinguptrees.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("12_lookinguptreesnight", "/assets/sprites/12_lookinguptreesnight.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("13_lostpathglow", "/assets/sprites/13_lostpathglow.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("14_woodenhouse", "/assets/sprites/14_woodenhouse.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("15_woodenhousepeek", "/assets/sprites/15_woodenhousepeek.png", { sliceX: 8, anims: {"idle":{"from":0,"to":3,"loop":true},"noticed":{"from":4,"to":7,"loop":true}} });
loadSprite("16_talkingtomonster", "/assets/sprites/16_talkingtomonster.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("17_theyrebehind", "/assets/sprites/17_theyrebehind.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("18_theygotyou", "/assets/sprites/18_theygotyou.png", { sliceX: 10, anims: {"idle":{"from":0,"to":4,"loop":true},"angry":{"from":5,"to":9,"loop":true}} });
loadSprite("19_youwakeup", "/assets/sprites/19_youwakeup.png", { sliceX: 10, anims: {"idle":{"from":0,"to":4,"loop":true},"wakeUp":{"from":5,"to":9,"loop":true}} });
loadSprite("1_marketentry", "/assets/sprites/1_marketentry.png", { sliceX: 16, anims: {"idle":{"from":0,"to":15,"loop":false},"opened":{"from":12,"to":15,"loop":true}} });
loadSprite("20_funnydog", "/assets/sprites/20_funnydog.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("21_cauldron", "/assets/sprites/21_cauldron.png", { sliceX: 12, anims: {"idle":{"from":0,"to":11,"loop":true}} });
loadSprite("22_monstershandincauldron", "/assets/sprites/22_monstershandincauldron.png", { sliceX: 12, anims: {"idle":{"from":0,"to":11,"loop":true}} });
loadSprite("23_pepperreveal", "/assets/sprites/23_pepperreveal.png", { sliceX: 4, anims: {"idle":{"from":0,"to":3,"loop":true}} });
loadSprite("24_monsterhaspepper", "/assets/sprites/24_monsterhaspepper.png", { sliceX: 8, anims: {"idle":{"from":0,"to":3,"loop":true},"lookingAtPlayer":{"from":4,"to":7,"loop":true}} });
loadSprite("25_holdingpepper", "/assets/sprites/25_holdingpepper.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("26_pain", "/assets/sprites/26_pain.png", { sliceX: 17, anims: {"idle":{"from":0,"to":16,"loop":false},"pain":{"from":11,"to":16,"loop":true}} });
loadSprite("27_lol", "/assets/sprites/27_lol.png", { sliceX: 22, anims: {"idle":{"from":0,"to":5,"loop":true},"transition":{"from":6,"to":21,"loop":false},"scary":{"from":16,"to":21,"loop":true}} });
loadSprite("28_milk", "/assets/sprites/28_milk.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("29_ending", "/assets/sprites/29_ending.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("2_chocolate", "/assets/sprites/2_chocolate.png", { sliceX: 4, anims: {"idle":{"from":0,"to":3,"loop":true}} });
loadSprite("3_milk", "/assets/sprites/3_milk.png", { sliceX: 4, anims: {"idle":{"from":0,"to":3,"loop":true}} });
loadSprite("4_mass", "/assets/sprites/4_mass.png", { sliceX: 4, anims: {"idle":{"from":0,"to":3,"loop":true}} });
loadSprite("5_casher", "/assets/sprites/5_casher.png", { sliceX: 4, anims: {"idle":{"from":0,"to":3,"loop":true}} });
loadSprite("6_path", "/assets/sprites/6_path.png", { sliceX: 6, anims: {"idle":{"from":0,"to":5,"loop":true}} });
loadSprite("7_forest", "/assets/sprites/7_forest.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("8_cursedpath", "/assets/sprites/8_cursedpath.png", { sliceX: 6, anims: {"idle":{"from":0,"to":5,"loop":true}} });
loadSprite("9_forestbed", "/assets/sprites/9_forestbed.png", { sliceX: 5, anims: {"idle":{"from":0,"to":4,"loop":true}} });
loadSprite("blank", "/assets/sprites/blank.png", { sliceX: 1, anims: {"idle":{"from":0,"to":0,"loop":false}} });
loadSound("1_marketambience", "/assets/sounds/music/1_marketambience.mp3");
loadSound("1_marketmusic", "/assets/sounds/music/1_marketmusic.mp3");
loadSound("2_forest", "/assets/sounds/music/2_forest.ogg");
loadSound("3_pain", "/assets/sounds/music/3_pain.ogg");
loadSound("4_aloneinforest", "/assets/sounds/music/4_aloneinforest.mp3");
loadSound("4_night", "/assets/sounds/music/4_night.ogg");
loadSound("5_wakeupinside", "/assets/sounds/music/5_wakeupinside.ogg");
loadSound("6_talkingtomonster", "/assets/sounds/music/6_talkingtomonster.ogg");
loadSound("7_youhavethepepper", "/assets/sounds/music/7_youhavethepepper.mp3");
loadSound("8_purgatory", "/assets/sounds/music/8_purgatory.mp3");
loadSound("1_slidingdoors", "/assets/sounds/sfx/1_slidingdoors.mp3");
loadSound("2_monsterappear", "/assets/sounds/sfx/2_monsterappear.mp3");
loadSound("3_monsterlooksatyou", "/assets/sounds/sfx/3_monsterlooksatyou.mp3");
loadSound("4_pain", "/assets/sounds/sfx/4_pain.ogg");
loadSound("5_pepperreveal", "/assets/sounds/sfx/5_pepperreveal.mp3");
loadSound("6_monsterreveal", "/assets/sounds/sfx/6_monsterreveal.mp3");
loadSound("7_phonering", "/assets/sounds/sfx/7_phonering.mp3");
loadSound("interaction", "/assets/sounds/sfx/interaction.mp3");
loadSound("intro", "/assets/sounds/sfx/intro.mp3");
loadSound("outro", "/assets/sounds/sfx/outro.mp3");
loadSound("casher", "/assets/sounds/talking/casher.mp3");
loadSound("monster", "/assets/sounds/talking/monster.mp3");
loadSound("monster_scary", "/assets/sounds/talking/monster_scary.mp3");